src/main/java/domain/Person.java
package domain;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 *
 * @author Erdem Akyıldız
 */
@Entity
public class Person implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID")
    private Long id;

    @Column(nullable = false)
    private String ad;
    @Column(nullable = false)
    private String soyad;


    public String getAd() {
        return ad;
    }

    public void setAd(String ad) {
        this.ad = ad;
    }

    public String getSoyad() {
        return soyad;
    }

    public void setSoyad(String soyad) {
        this.soyad = soyad;
    }


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Person)) {
            return false;
        }
        Person other = (Person) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "domain.Person[ id=" + id + " ]";
    }

}

src/main/java/com/erdem/IndexBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.erdem;

import domain.Person;
import java.io.IOException;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import org.primefaces.context.RequestContext;
import service.PersonService;

/**
 *
 * @author Erdem Akyıldız
 */
@ManagedBean(name = "IndexBean")
@SessionScoped
public class IndexBean {

    @EJB
    PersonService personService;

    private Person person = new Person();
    private String commandButtonValue = "Ekle";

    public String getCommandButtonValue() {
        return commandButtonValue;
    }

    public void setCommandButtonValue(String commandButtonValue) {
        this.commandButtonValue = commandButtonValue;
    }


    public Person getPerson() {
        return person;
    }

    public void setPerson(Person person) {
        this.person = person;
    }

    public void savePerson() throws IOException {
        FacesMessage message = new FacesMessage();
        if (person.getAd().equals("") || person.getSoyad().equals("")) {
            message.setSummary("Hata");
            message.setDetail("Alanları Boş Bırakmayın");
            RequestContext.getCurrentInstance().showMessageInDialog(message);
            return;
        }
        if (getCommandButtonValue().equals("Ekle")){
            personService.save(person);
            person = new Person();
        }else{
            personService.updatePerson(person);
            setCommandButtonValue("Ekle");
        }
        
        person = new Person();
    }

    public List<Person> getPersons() {
        return personService.getAllPerson();
    }

    public void deletePerson(Person person) {
        personService.deletePerson(person);
    }
    
    public void updatePerson(Person person) {
        this.person = person;
        setCommandButtonValue("Güncelle");
    }

}

src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>JSF Crud App</title>
    </h:head>
    <h:body>
        <h:form id="form">
            <p:panelGrid columns="2" id="addPerson">
                <p:outputLabel value="Ad : "/>
                <p:inputText value="#{IndexBean.person.ad}" />

                <p:outputLabel value="Soyad : "/>
                <p:inputText value="#{IndexBean.person.soyad}" />
                
                <p:commandButton action="#{IndexBean.savePerson()}" value="#{IndexBean.commandButtonValue}" update=":form" />
            </p:panelGrid>
            

            <p:dataTable var="person" value="#{IndexBean.persons}" id="showPersonList">
                <f:facet name="header">
                    Ekli Kişiler
                </f:facet>
                <p:column headerText="ID">
                    <h:outputText value="#{person.id}" />
                </p:column>
                <p:column headerText="AD">
                    <h:outputText value="#{person.ad}" />
                </p:column>
                <p:column headerText="SOYAD">
                    <h:outputText value="#{person.soyad}" />
                </p:column>
                
                <p:column headerText="İşlemler">
                    <p:commandButton value="Sil" action="#{IndexBean.deletePerson(person)}" update=":form:showPersonList"/>
                    <p:commandButton value="Guncelle" action="#{IndexBean.updatePerson(person)}" update=":form:addPerson"/>
                </p:column>
            </p:dataTable>
        </h:form>
    </h:body>
</html>